name = "Word2Vec"
uuid = "07718ad2-0e07-11eb-1044-2f7de2a2b708"
author = ["Corneliu Cofaru <cornel@oxoaresearch.com>"]
version = "0.5.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
